apiVersion: v1
kind: Service
metadata:
  name: web-svc
  namespace: demo
spec:
  type: NodePort        # simple to test on Minikube
  selector:
    app: web
  ports:
    - name: http
      port: 80
      targetPort: 80
